apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: techdome-backend-pvc
  namespace: techdome
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1G
