# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techdome-backend-deployment
  namespace: techdome
  labels:
    app: techdome-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: techdome-backend
  template:
    metadata:
      labels:
        app: techdome-backend
    spec:
      containers:
      - name: techdome-backend
        image: uj5ghare/techdome-backend:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
          - name: DB
            value: "mongodb://mongodb-svc:27017"