# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: techdome-backend-svc
  namespace: techdome
  labels:
    app: techdome-backend
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: techdome-backend
  type: ClusterIP