apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  namespace: techdome
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi